# Generated by Django 3.2.13 on 2022-12-26 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ietf_language_tags', '0004_auto_20200804_1401'),
        ('course_metadata', '0276_add_bootcamp_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ietf_language_tags.languagetag'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='level',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.leveltype'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.subject'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='topic',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.topic'),
        ),
        migrations.AddField(
            model_name='program',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ietf_language_tags.languagetag'),
        ),
        migrations.AddField(
            model_name='program',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_metadata.leveltype'),
        ),
        migrations.AddField(
            model_name='program',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_metadata.subject'),
        ),
        migrations.AddField(
            model_name='program',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_metadata.topic'),
        ),
    ]
