# Generated by Django 3.2.13 on 2022-12-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0277_auto_20221226_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='assignment_due',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='enrollment_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='assignment_due',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='enrollment_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
