# Generated by Django 3.2.13 on 2022-12-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0278_auto_20221226_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprogram',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='end',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
