# Generated by Django 3.2.13 on 2022-12-26 10:04

import course_discovery.apps.course_metadata.fields
import course_discovery.apps.course_metadata.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0279_auto_20221226_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='certificte_overview',
            field=course_discovery.apps.course_metadata.fields.HtmlField(null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html], verbose_name='Program Certificate Overview'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='ebooks_overview',
            field=course_discovery.apps.course_metadata.fields.HtmlField(null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html], verbose_name='E-Books from EBC Reader Overview'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='live_class_overview',
            field=course_discovery.apps.course_metadata.fields.HtmlField(null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html], verbose_name='Demo Live Classes Overview'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='placement_overview',
            field=course_discovery.apps.course_metadata.fields.HtmlField(null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html], verbose_name='INTERNSHIP & PLACEMENT PARTNERS Overview'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='price_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='certificte_overview',
            field=course_discovery.apps.course_metadata.fields.HtmlField(null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html], verbose_name='Program Certificate Overview'),
        ),
        migrations.AddField(
            model_name='program',
            name='ebooks_overview',
            field=course_discovery.apps.course_metadata.fields.HtmlField(null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html], verbose_name='E-Books from EBC Reader Overview'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='live_class_overview',
            field=course_discovery.apps.course_metadata.fields.HtmlField(null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html], verbose_name='Demo Live Classes Overview'),
        ),
        migrations.AddField(
            model_name='program',
            name='placement_overview',
            field=course_discovery.apps.course_metadata.fields.HtmlField(null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html], verbose_name='INTERNSHIP & PLACEMENT PARTNERS Overview'),
        ),
        migrations.AddField(
            model_name='program',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='price_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
