# Generated by Django 3.2.13 on 2022-12-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0280_auto_20221226_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogram',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
