# Generated by Django 3.2.13 on 2022-12-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0283_auto_20221226_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprogram',
            old_name='enrollment_start',
            new_name='enrollment_end',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='enrollment_start',
            new_name='enrollment_end',
        ),
    ]
