# Generated by Django 3.2.13 on 2023-03-20 07:22

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_first_name'),
        ('course_metadata', '0284_auto_20221228_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='authoring_organizations',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='authored_courses', to='course_metadata.Organization', verbose_name='Partners'),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='partner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.partner', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='program',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.partner', verbose_name='Institution'),
        ),
    ]
