# Generated by Django 3.2.13 on 2023-03-20 10:03

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0285_auto_20230320_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='authoring_organizations',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='authored_courses', to='course_metadata.Organization'),
        ),
        migrations.AlterField(
            model_name='program',
            name='authoring_organizations',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='authored_programs', to='course_metadata.Organization', verbose_name='Partners'),
        ),
    ]
