# Generated by Django 3.2.13 on 2023-04-23 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0286_auto_20230320_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='program',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='ebooks_overview',
            field=models.TextField(blank=True, null=True, verbose_name='What’s included?'),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.subject', verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='program',
            name='ebooks_overview',
            field=models.TextField(blank=True, null=True, verbose_name='What’s included?'),
        ),
        migrations.AlterField(
            model_name='program',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_metadata.subject', verbose_name='Purpose'),
        ),
    ]
