# Generated by Django 3.2.13 on 2023-07-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0288_auto_20230529_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='purchase_url',
            field=models.CharField(blank=True, help_text='Enter third party website program purchase URL.', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='purchase_url',
            field=models.CharField(blank=True, help_text='Enter third party website program purchase URL.', max_length=1024, null=True),
        ),
    ]
