# Generated by Django 3.2.13 on 2023-07-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0290_auto_20230706_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogram',
            name='partner_display',
            field=models.CharField(blank=True, help_text='Enter the programme institution you want to have on the show.The institution you chose in previous institution is overridden by this setting. To use the chosen institution, leave it empty.', max_length=512, null=True, verbose_name='Institution Display String'),
        ),
        migrations.AlterField(
            model_name='program',
            name='partner_display',
            field=models.CharField(blank=True, help_text='Enter the programme institution you want to have on the show.The institution you chose in previous institution is overridden by this setting. To use the chosen institution, leave it empty.', max_length=512, null=True, verbose_name='Institution Display String'),
        ),
    ]
