# Generated by Django 3.2.13 on 2023-07-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0291_auto_20230706_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='campaign_code',
            field=models.TextField(blank=True, null=True, verbose_name='Campaign embed code'),
        ),
        migrations.AddField(
            model_name='program',
            name='campaign_code',
            field=models.TextField(blank=True, null=True, verbose_name='Campaign embed code'),
        ),
    ]
