# Generated by Django 3.2.13 on 2023-08-01 04:12

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0292_auto_20230710_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='instructor_ordering_title',
            field=models.CharField(default='Instructors', max_length=512),
        ),
        migrations.AddField(
            model_name='program',
            name='instructor_ordering_title',
            field=models.CharField(default='Instructors', max_length=512),
        ),
        migrations.CreateModel(
            name='InstructorBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=1024)),
                ('instructor_ordering', sortedm2m.fields.SortedManyToManyField(blank=True, help_text='This field can be used by API clients to determine the order in which instructors will be displayed on program pages. Instructors in this list should appear before all others associated with this programs courses runs.', to='course_metadata.Person')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_metadata.program')),
            ],
            options={
                'verbose_name': 'InstructorBlocks',
                'verbose_name_plural': 'Instructor Blocks',
            },
        ),
    ]
