# Generated by Django 3.2.13 on 2023-12-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0293_auto_20230801_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='advertised_start',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Programme Advertised Start'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='advertised_start',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Programme Advertised Start'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
