# Generated by Django 3.2.13 on 2023-12-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0294_auto_20231227_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='introduction_video',
            field=models.TextField(blank=True, help_text='Enter Brightcove video embed code here.', null=True, verbose_name='Brightcove Programme Introduction Video'),
        ),
        migrations.AddField(
            model_name='program',
            name='introduction_video',
            field=models.TextField(blank=True, help_text='Enter Brightcove video embed code here.', null=True, verbose_name='Brightcove Programme Introduction Video'),
        ),
    ]
