# Generated by Django 3.2.13 on 2024-01-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0295_auto_20231228_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='upgrade_deadline',
            field=models.DateField(blank=True, help_text='After this date/time, users will no longer be able to purchase programme.Leave this blank if users can purchase this programme until enrollment closes.NOTE: Upgrade Deadline date must be later than the programme enrollment end date.', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='upgrade_deadline',
            field=models.DateField(blank=True, help_text='After this date/time, users will no longer be able to purchase programme.Leave this blank if users can purchase this programme until enrollment closes.NOTE: Upgrade Deadline date must be later than the programme enrollment end date.', null=True),
        ),
    ]
