# Generated by Django 3.2.13 on 2024-01-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0296_auto_20240102_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='access_duration',
            field=models.PositiveIntegerField(default=365, help_text='Enter the duration of the programme in days. This duration will be used to set the course access end date once a user enrolls into the programme.', verbose_name='Programme Access Duration (in days)'),
        ),
        migrations.AddField(
            model_name='program',
            name='access_duration',
            field=models.PositiveIntegerField(default=365, help_text='Enter the duration of the programme in days. This duration will be used to set the course access end date once a user enrolls into the programme.', verbose_name='Programme Access Duration (in days)'),
        ),
    ]
