# Generated by Django 3.2.13 on 2024-02-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0298_auto_20240208_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='video_block_title',
            field=models.CharField(blank=True, max_length=2056, null=True, verbose_name='Video Block Title'),
        ),
        migrations.AddField(
            model_name='program',
            name='video_block_title',
            field=models.CharField(blank=True, max_length=2056, null=True, verbose_name='Video Block Title'),
        ),
        migrations.AlterField(
            model_name='videosblock',
            name='title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
