# Generated by Django 3.2.13 on 2024-03-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0299_auto_20240209_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='in_subscription',
            field=models.BooleanField(default=False, verbose_name='Include programme in subscription?'),
        ),
        migrations.AddField(
            model_name='program',
            name='in_subscription',
            field=models.BooleanField(default=False, verbose_name='Include programme in subscription?'),
        ),
    ]
