# Generated by Django 3.2.13 on 2024-05-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0300_auto_20240318_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='seo_title',
            field=models.CharField(blank=True, max_length=2056, null=True, verbose_name='Programme SEO Title'),
        ),
        migrations.AddField(
            model_name='program',
            name='seo_title',
            field=models.CharField(blank=True, max_length=2056, null=True, verbose_name='Programme SEO Title'),
        ),
    ]
