# Generated by Django 3.2.13 on 2024-08-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0303_auto_20240711_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='effort',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='effort',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
