# Generated by Django 3.2.13 on 2024-09-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0304_auto_20240825_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='offer_text',
            field=models.TextField(blank=True, help_text='Enter a short offer or discounts notes to be displayed below the price on the programm about page. This note could include information like limited-time offers, discounts, or strike price etc. Leave blank if no additional note is required.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='offer_text',
            field=models.TextField(blank=True, help_text='Enter a short offer or discounts notes to be displayed below the price on the programm about page. This note could include information like limited-time offers, discounts, or strike price etc. Leave blank if no additional note is required.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='effort',
            field=models.CharField(blank=True, help_text='Insert hours and minutes for self-paced programmes.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='price_text',
            field=models.TextField(blank=True, help_text='Enter a brief note or promotional message to be displayed below the price on the programme about page. This note could include information like included subscription, price for annual etc. Leave blank if no additional note is required.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='effort',
            field=models.CharField(blank=True, help_text='Insert hours and minutes for self-paced programmes.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='price_text',
            field=models.TextField(blank=True, help_text='Enter a brief note or promotional message to be displayed below the price on the programme about page. This note could include information like included subscription, price for annual etc. Leave blank if no additional note is required.', max_length=255, null=True),
        ),
    ]
