# Generated by Django 3.2.13 on 2024-09-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0305_auto_20240910_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogram',
            name='offer_text',
            field=models.TextField(blank=True, help_text='Enter a short offer or discounts notes to be displayed below the price on the programm about page. This note could include information like limited-time offers, discounts, or strike price etc. Leave blank if no additional note is required.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='price_text',
            field=models.TextField(blank=True, help_text='Enter a brief note or promotional message to be displayed below the price on the programme about page. This note could include information like included subscription, price for annual etc. Leave blank if no additional note is required.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='tax_info',
            field=models.CharField(blank=True, default='Price not inclusive of GST', max_length=1024, null=True, verbose_name='Tax Information'),
        ),
        migrations.AlterField(
            model_name='program',
            name='offer_text',
            field=models.TextField(blank=True, help_text='Enter a short offer or discounts notes to be displayed below the price on the programm about page. This note could include information like limited-time offers, discounts, or strike price etc. Leave blank if no additional note is required.', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='price_text',
            field=models.TextField(blank=True, help_text='Enter a brief note or promotional message to be displayed below the price on the programme about page. This note could include information like included subscription, price for annual etc. Leave blank if no additional note is required.', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='tax_info',
            field=models.CharField(blank=True, default='Price not inclusive of GST', max_length=1024, null=True, verbose_name='Tax Information'),
        ),
    ]
