# Generated by Django 3.2.13 on 2024-10-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0306_auto_20240917_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='enrollment_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='enrollment_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
