# Generated by Django 3.2.13 on 2024-10-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0308_auto_20241009_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='additional_campaign_info',
            field=models.TextField(blank=True, help_text='Enter the HTML code(like buttons, links) to be displayed on the program about page below start date, price, instutiton etc information', null=True, verbose_name='Additional Campaign information'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='enrollment_info',
            field=models.CharField(blank=True, help_text='Enter information to be displayed on top of enrollment button on the  program about page', max_length=1024, null=True, verbose_name='Enrollment Information'),
        ),
        migrations.AddField(
            model_name='program',
            name='additional_campaign_info',
            field=models.TextField(blank=True, help_text='Enter the HTML code(like buttons, links) to be displayed on the program about page below start date, price, instutiton etc information', null=True, verbose_name='Additional Campaign information'),
        ),
        migrations.AddField(
            model_name='program',
            name='enrollment_info',
            field=models.CharField(blank=True, help_text='Enter information to be displayed on top of enrollment button on the  program about page', max_length=1024, null=True, verbose_name='Enrollment Information'),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='advertised_start',
            field=models.CharField(blank=True, help_text='Enter information to be displayed insted of start date on the program about page', max_length=1024, null=True, verbose_name='Programme Advertised Start'),
        ),
        migrations.AlterField(
            model_name='program',
            name='advertised_start',
            field=models.CharField(blank=True, help_text='Enter information to be displayed insted of start date on the program about page', max_length=1024, null=True, verbose_name='Programme Advertised Start'),
        ),
    ]
