# Generated by Django 3.2.13 on 2024-11-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0309_auto_20241010_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='content_activation_window',
            field=models.CharField(blank=True, help_text="Define the content access period (e.g., '3-Year Access').", max_length=1024, null=True, verbose_name='Content Activation Window'),
        ),
        migrations.AddField(
            model_name='program',
            name='content_activation_window',
            field=models.CharField(blank=True, help_text="Define the content access period (e.g., '3-Year Access').", max_length=1024, null=True, verbose_name='Content Activation Window'),
        ),
    ]
