# Generated by Django 3.2.13 on 2024-11-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0310_auto_20241118_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogram',
            name='content_activation_window',
            field=models.CharField(blank=True, help_text="Enter the programme access period (e.g., '3-Year Access'). This will be displayed on the program about page after start date, price, instutiton etc information", max_length=1024, null=True, verbose_name='Programme Access Duration Text'),
        ),
        migrations.AlterField(
            model_name='program',
            name='content_activation_window',
            field=models.CharField(blank=True, help_text="Enter the programme access period (e.g., '3-Year Access'). This will be displayed on the program about page after start date, price, instutiton etc information", max_length=1024, null=True, verbose_name='Programme Access Duration Text'),
        ),
    ]
