# Generated by Django 3.2.13 on 2025-01-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0311_auto_20241118_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='preview_button_1',
            field=models.TextField(blank=True, help_text='Enter HTML content to be displayed below program title and subtitle on the program about page', max_length=1024, null=True, verbose_name='Preview Button 1'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='preview_button_2',
            field=models.TextField(blank=True, help_text='Enter HTML content to be displayed below program title and subtitle on the program about page', max_length=1024, null=True, verbose_name='Preview Button 2'),
        ),
        migrations.AddField(
            model_name='program',
            name='preview_button_1',
            field=models.TextField(blank=True, help_text='Enter HTML content to be displayed below program title and subtitle on the program about page', max_length=1024, null=True, verbose_name='Preview Button 1'),
        ),
        migrations.AddField(
            model_name='program',
            name='preview_button_2',
            field=models.TextField(blank=True, help_text='Enter HTML content to be displayed below program title and subtitle on the program about page', max_length=1024, null=True, verbose_name='Preview Button 2'),
        ),
    ]
