# Generated by Django 3.2.13 on 2025-01-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0312_auto_20250107_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogram',
            name='preview_button_1',
            field=models.TextField(blank=True, help_text='Enter HTML content to be displayed below program title and subtitle on the program about page', null=True, verbose_name='Preview Button 1'),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='preview_button_2',
            field=models.TextField(blank=True, help_text='Enter HTML content to be displayed below program title and subtitle on the program about page', null=True, verbose_name='Preview Button 2'),
        ),
        migrations.AlterField(
            model_name='program',
            name='preview_button_1',
            field=models.TextField(blank=True, help_text='Enter HTML content to be displayed below program title and subtitle on the program about page', null=True, verbose_name='Preview Button 1'),
        ),
        migrations.AlterField(
            model_name='program',
            name='preview_button_2',
            field=models.TextField(blank=True, help_text='Enter HTML content to be displayed below program title and subtitle on the program about page', null=True, verbose_name='Preview Button 2'),
        ),
    ]
