# Generated by Django 3.2.13 on 2025-10-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0313_auto_20250108_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsocialnetwork',
            name='type',
            field=models.CharField(choices=[('blog', 'Blog'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('others', 'Others'), ('twitter', 'Twitter')], db_index=True, max_length=15),
        ),
    ]
